version: "3.9"
services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - teamstructor.test
    volumes:
      - ./src/teamstructor-app:/var/www/html:cached

  teamstructor.test:
    build: ./docker/php/
    expose:
      - 9000
    working_dir: /var/www/html/
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    links:
      - db
    volumes:
      - ./src/teamstructor-app:/var/www/html:cached

  db:
    platform: linux/x86_64
    image: mysql:5.7
    user: root
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/mysql:/docker-entrypoint-initdb.d
      - mysql-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    build: ./docker/phpmyadmin/
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
    volumes:
        - minio-data:/data
    command: server /data --console-address :9001

  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  mysql-db-data:
  minio-data:
